name: Deploy Archive

on:
  workflow_dispatch:
  schedule:
    - cron: 0/60 * * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish zulip-archive on GH Pages
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: zulip/zulip-archive@bcd29a173500de778e70a304fc40cdffaec78803
        with:
          zulip_organization_url: ${{ secrets.ZULIP_ORGANISATION_URL }}
          zulip_bot_email: ${{ secrets.ZULIP_BOT_EMAIL }}
          zulip_bot_key: ${{ secrets.ZULIP_BOT_KEY }}
          github_personal_access_token: ${{ secrets.DEPLOY_PAT }}
          delete_history: true
