name: Deploy Archive

on:
  workflow_dispatch:
  schedule:
    - cron: 30 4 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish zulip-archive on GH Pages
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: zulip/zulip-archive@5ff607209cbd3a7ff74cbca84656d01bfc8b5929
        with:
          zulip_organization_url: ${{ secrets.ZULIP_ORGANISATION_URL }}
          zulip_bot_email: ${{ secrets.ZULIP_BOT_EMAIL }}
          zulip_bot_key: ${{ secrets.ZULIP_BOT_KEY }}
          # archive_branch: main
          
          github_personal_access_token: ${{ secrets.DEPLOY_PAT }}
          delete_history: true
