name: Deploy Archive

on:
  workflow_dispatch:
  schedule:
    - cron: 30 4 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish zulip-archive on GH Pages
    steps:
      - uses: actions/checkout@v4
      - uses: zulip/zulip-archive@5ff607209cbd3a7ff74cbca84656d01bfc8b5929
        with:
          zuliprc: ${{ secrets.ZULIPRC }}
          # archive_branch: main
          
          github_token: ${{ secrets.DEPLOY_PAT }}
          delete_history: true
